### ISSUE TITLE
Docker compose fails

### ISSUE THREAD

**Issue by sher1** [changeweb/Unifiedtransform#109]
**Describe the bug**
The docker-compose up -d fails. Tried running non-daemon and fails in same place

**To Reproduce**
1. Run docker-compose up -d
Here is the output after starting with the build container:
Build complete.
Don't forget to run 'make test'.

Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20170718/
Installing header files:          /usr/local/include/php/
find . -name \*.gcno -o -name \*.gcda | xargs rm -f
find . -name \*.lo -o -name \*.o | xargs rm -f
find . -name \*.la -o -name \*.a | xargs rm -f
find . -name \*.so | xargs rm -f
find . -name .libs -a -type d|xargs rm -rf
rm -f libphp.la       modules/* libs/*
Removing intermediate container e70af477d41e
 ---> ddbb834e889d
Step 9/22 : RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
 ---> Running in c55c8e4d76c9
All settings correct for using Composer
Downloading...

Composer (version 1.8.5) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer

Removing intermediate container c55c8e4d76c9
 ---> a2ee463e778f
Step 10/22 : RUN groupadd -g 1000 www
 ---> Running in 2e028056fedf
Removing intermediate container 2e028056fedf
 ---> cc5484e6d6f1
Step 11/22 : RUN useradd -u 1000 -ms /bin/bash -g www www
 ---> Running in 4e5c4947c083
Removing intermediate container 4e5c4947c083
 ---> 8dde88ad551c
Step 12/22 : COPY . /var/www
 ---> f7eb563798e1
Step 13/22 : COPY --chown=www:www . /var/www
 ---> 3423b85ae89c
Step 14/22 : USER www
 ---> Running in a26307cda5cf
Removing intermediate container a26307cda5cf
 ---> b132261fac73
Step 15/22 : RUN composer install
 ---> Running in c59b9fe4b987
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Package operations: 104 installs, 0 updates, 0 removals

                                                            
  [RuntimeException]                                        
  /var/www/vendor does not exist and could not be created.  
                                                            

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

ERROR: Service 'app' failed to build: The command '/bin/sh -c composer install' returned a non-zero code: 1

I expected the containers to start

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 64bit

I was just trying to get the containers to complete so I could look at the tool

**Comment by changeweb** [comment]
@sher1 I changed the `composer.json` and forgot to update the `composer.lock` file. I've updated the master branch with new changes. Let me know if this works for you.

**Comment by changeweb** [comment]
You also need to change mysql user and password in docker-compose.yml or .env.

BTW could you tell me in which directory you put your cloned repo?

And what you docker commands you ran before running `docker-compose up -d`?

**Comment by changeweb** [comment]
@mykeels I'm also getting the same error. It would be great if you can help and it is your area of expertise also.

**Comment by mykeels** [comment]
Looks like this is the errant line

https://github.com/changeweb/Unifiedtransform/blob/bf8945fe17d7e5bdf281855c55f8b9f643bf4edb/Dockerfile#L48

I think it should have been `RUN composer update` rather than `install`. Can you try changing that and see if it works @sher1?

**Comment by changeweb** [comment]
@mykeels I change it to `composer update` and still got the same error. I think the error is about path of `var\www\` and permission related.

![Screenshot from 2019-04-17 14-31-55](https://user-images.githubusercontent.com/9896315/56273345-600eb300-611e-11e9-9bd4-e215dfdfb94a.png)

**Comment by changeweb** [comment]
@mykeels  Or are we missing anything while setting up Docker and Docker composer? Can you please share your steps of setting this software using Docker?

**Comment by mykeels** [comment]
I'm checking [this issue thread](https://github.com/panique/huge/issues/392) out. Looks like the appropriate permissions for the `/var/www` folder are not set.

**Comment by changeweb** [comment]
Ok, so `chmod -R 777 /var/www` is the most accepted answer. Though we better use `775`

**Comment by mykeels** [comment]
Placing the RUN scripts before the `USER www` line fixes this.

```sh
# Copy existing application directory permissions
COPY --chown=www:www . /var/www

RUN composer install --no-plugins --no-scripts
RUN php artisan key:generate
RUN php artisan config:cache
RUN npm install
RUN npm run dev

# Change current user to www
USER www
```

However, the The `Dockerfile` definitely needs updates. I should submit another PR today. I just realised I didn't make provision for `node`.

**Comment by changeweb** [comment]
@mykeels Composer problem is now solved but `php artisan` command not working.

![Screenshot from 2019-04-17 16-47-46](https://user-images.githubusercontent.com/9896315/56282863-f6000900-6131-11e9-833b-af3bba7ab713.png)

**Comment by mykeels** [comment]
Did you run `composer install --no-plugins --no-scripts` or `composer update`?

**Comment by changeweb** [comment]
`composer install --no-plugins --no-scripts`. This works fine. The problem is about PHP artisan

**Comment by changeweb** [comment]
@mykeels See this [Can't run a command from Dockerfile or Docker Compose](https://stackoverflow.com/q/39981342). I'm facing exact same problem. The solution to it is to run `php artisan` after image build. Like `docker-compose run workspace php artisan key:generate`. What is your opinion?

**Comment by changeweb** [comment]
I've found a work around. I'll document the instructions on how to use Docker container for this app in readme.md.

**Comment by sher1** [comment]
I went away for a week and you guys worked through all of the issues without me. Well done
