### ISSUE TITLE
Please provide install instructions for dumb

### ISSUE THREAD

**Issue by Khmelovsky** [changeweb/Unifiedtransform#116]
Thank you so much for your  work! 
I would  like use this application, but  I ca not not start in locally  in docker

Could you  please provide  detailed  step by step guide? 

Thanks in advance,
Andrii

**Comment by narenknn** [comment]
me too .. I also have a very basic webserver with PHP. I couldn't do the first step... "composer.phar" is missing.

**Comment by narenknn** [comment]
did "composer install" and I think I made progress.. doing other steps.. may be you can try and update me too...

**Comment by narenknn** [comment]
I was able to successfully deploy the application .. Just follow the instructions except for the first one. It also created a random school, but that's OK. Webserver should be pointing to the 'public' directory.

**Comment by changeweb** [comment]
@Khmelovsky @narenknn The instructions are already very simple.

You can install this software in two ways:

     1. Using a container like Docker
     2. Not using a container

For Docker installation you need to have Docker and Docker Compose installed. Then follow the instructions in readme.md. Our Docker setup uses Nginx, Mysql and PHP, Composer. So you don't have to install them separately.

For installation without a container is simple too. You need to just have setup servers of your choice. XAMPP is a good start for this. You need to install Composer also before progressing to further instructions given in readme.md.

Hope this helps.

**Comment by Khmelovsky** [comment]
Hi @changeweb, 
Thank you for  your response  but  I'm still little confused.  
I'm using  Docker approach  and  after  longing to bash I cannot  execute other command  and  install  composer in a container.
I guess  Docker file dependencies is  not installing.

Could  you please give me a advice  where I am wrong? 
Thanks  in advance,
Andrii.

**Comment by changeweb** [comment]
@Khmelovsky could you share the steps and commands you tried with screenshots?

**Comment by mykeels** [comment]
Turns out the instructions for installing without a container might be flawed. 

> If you attempt to `composer install` without copying the `.env` from `.env.example`, composer will assume you're in a production environment, and Dusk setup will fail.

Following a request from Fernando Velasquez, I made a video guide, embedded in this article, showing how to get setup.

https://medium.com/@mykeels/unifiedtransform-getting-started-90543e0c135

**Comment by Khmelovsky** [comment]
@mykeels  Thank you so much, my problem  solved!  Very useful tutorial for everyone!

**Comment by Khmelovsky** [comment]
@mykeels  Thank you so much, my problem  solved!  Very useful tutorial for everyone!

**Comment by changeweb** [comment]
@mykeels awesome work!!

Will you publish the article? Is it ok if I add this guide url in readme? Or you may create a pull request.

Thanks for spending your precious time and knowledge.

**Comment by mykeels** [comment]
Thanks, guys.

I think it's better to make a PR, and maybe embed the video in the README, than publish the article, so all instructions are in the repo, and under version control. @changeweb

**Comment by changeweb** [comment]
@mykeels then please change the order of `composer install` and `cp .env.example .env` in readme in your PR.

**Comment by shreyaspapi** [comment]
Can someone please make such video for ubuntu (On Production). Many people are having issues with it.

**Comment by She110ck** [comment]
Hi everyone. Installation via docker doesn't work:

`
Scaffolding your app using Docker... This will take a while...
Creating network "unifiedtransform_app-network" with driver "bridge"
Creating db  ... done
Creating php ... done
Creating composer   ... done
Creating artisan    ... done
Creating phpmyadmin ... done
Creating nginx      ... done
Creating unifiedtransform_composer_run ... done
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 146 installs, 0 updates, 0 removals

                                                                 
  [RuntimeException]                                             
  /var/www/html/vendor does not exist and could not be created.  
                                                                 

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...

Creating unifiedtransform_artisan_run ... done

Warning: require(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/artisan on line 18

Fatal error: require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/artisan on line 18
\nUnifiedtransform is ready on localhost:4049 and localhost:5051 for the PHPMyAdmin\n
`

**Comment by mykeels** [comment]
Hi, I'll give this a shot.

**Comment by mykeels** [comment]
@She110ck running `docker-install.sh` in bash, worked for me. How did you try the docker installation?

**Comment by She110ck** [comment]
@mykeels I ran `docker-install.sh` got error. So tried install on host, its worked.

**Comment by waseemsamra** [comment]
With docker installation everything is fine, but unable to login with master username with password. @mykeels need your help for master password.

**Comment by imranzahid01** [comment]
> Hi everyone. Installation via docker doesn't work:
> 
> ```
> Scaffolding your app using Docker... This will take a while...
> Creating network "unifiedtransform_app-network" with driver "bridge"
> Creating db  ... done
> Creating php ... done
> Creating composer   ... done
> Creating artisan    ... done
> Creating phpmyadmin ... done
> Creating nginx      ... done
> Creating unifiedtransform_composer_run ... done
> Installing dependencies from lock file (including require-dev)
> Verifying lock file contents can be installed on current platform.
> Package operations: 146 installs, 0 updates, 0 removals
> 
>                                                                  
>   [RuntimeException]                                             
>   /var/www/html/vendor does not exist and could not be created.  
>                                                                  
> 
> install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...
> 
> Creating unifiedtransform_artisan_run ... done
> 
> Warning: require(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/artisan on line 18
> 
> Fatal error: require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/artisan on line 18
> \nUnifiedtransform is ready on localhost:4049 and localhost:5051 for the PHPMyAdmin\n
> ```

I am having the exact same problems, how did you solve this?

**Comment by sjsajju** [comment]
@imranzahid01 @mykeels @changeweb i am having the same issue when running from docker. Has anybody really resolved this issue?s

**Comment by handhikadj** [comment]
@She110ck Did you try to run `chmod -R 777 .` on the project root? (Don't use `777` in production tho)

**Comment by usman-rind** [comment]
all setup through docker gone well, Although i executed the three statements as below but it failed on seed 
with the error of unable to connect with the db the same error happens when i am trying to connect to my sql through my sql admin using the user name and pass words generated in the .env file. Below is the screen shot of error could you please help me.

 docker-compose up -d
docker-compose run --rm composer install
docker-compose run --rm artisan migrate:fresh --seed
![image](https://user-images.githubusercontent.com/60088877/134981580-9d049e3a-7365-4588-b844-e495f098fce0.png)

**Comment by FormadorLar** [comment]
> Hi everyone. Installation via docker doesn't work:
> 
> ```
> Scaffolding your app using Docker... This will take a while...
> Creating network "unifiedtransform_app-network" with driver "bridge"
> Creating db  ... done
> Creating php ... done
> Creating composer   ... done
> Creating artisan    ... done
> Creating phpmyadmin ... done
> Creating nginx      ... done
> Creating unifiedtransform_composer_run ... done
> Installing dependencies from lock file (including require-dev)
> Verifying lock file contents can be installed on current platform.
> Package operations: 146 installs, 0 updates, 0 removals
> 
>                                                                  
>   [RuntimeException]                                             
>   /var/www/html/vendor does not exist and could not be created.  
>                                                                  
> 
> install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...
> 
> Creating unifiedtransform_artisan_run ... done
> 
> Warning: require(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/artisan on line 18
> 
> Fatal error: require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/artisan on line 18
> \nUnifiedtransform is ready on localhost:4049 and localhost:5051 for the PHPMyAdmin\n
> ```

anyone with a solution?
