### ISSUE TITLE
Add Impersonation

### ISSUE THREAD

**Issue by mykeels** [changeweb/Unifiedtransform#117]
**Is your feature request related to a problem? Please describe.**
When testing, I have to logout and login as the user I need to use. 

**Describe the solution you'd like**
With [Laravel Impersonate](https://github.com/404labfr/laravel-impersonate), I can pick a user I'd like to impersonate and see the application through that user's eyes. This is really helpful when testing.

We can have an "Impersonate" link/button on the user profile dropdown at the top-right of the screen, allowing the user to select a user besides themselves to impersonate.

**Additional context**
This feature can be made only accessible in dev/staging environment, for security reasons. 

A more advanced approach will be allowing users in a higher role/state-hierarchy to impersonate users under them. E.g. A `master` should be able to impersonate any of

- admin
- accountant
- librarian
- teacher
- student 

An admin can only impersonate 

- accountant
- librarian
- teacher
- student

**Comment by changeweb** [comment]
This is already done in feature test using `states`. So you want it to be visual also, right? If it can be done, it will be great. Right now I'm only focused on making the software more testable and bug free.

It will be great if you can help.
