### ISSUE TITLE
Issues found in Xampp

### ISSUE THREAD

**Issue by ekreddy** [changeweb/Unifiedtransform#138]
**Describe the bug**
1.Not able to create fee structure for class not not able to see fees for students
2. Not able to print student info/fee > export will be a great option
3. If syllabus can visible to students it will be great help , we can keep links to our LMS
4. Any documentation to host via Cpanel ?

**Comment by changeweb** [comment]
@ekreddy you can go **Fees Generator > Add Fee Field** and then go to **Fees Generator > Generate Form", select your desired fileds to add in the Fees form and then print using the Right Top green button.

You can print student info from student's profile page. Click a student's name to go to profile page.

Viewing syllabus from the web app will be great.

For Cpanel you can run `composer install` and `php artisan key:generate` commands in your local PC then upload the files via ftp and then create your database manually and table by php scripts. See the migration files and you will get help.
