### ISSUE TITLE
Registering a new admin for a new school is not possible

### ISSUE THREAD

**Issue by rowild** [changeweb/Unifiedtransform#14]
After filling out the info and hitting the save "Register" button, the site reloads the register site, but without saving the data to the DB (looking into the DB, no new user was added).

As a side note: IMO, the registration site should have a button that leads back to the "Manage school" site. Otherwise, you are stuck on the registration site forever...

**Comment by rowild** [comment]
Also, being on the register page and just clicking "Register" without providing any data won't trigger any errors... (like: "This field is required.")

**Comment by changeweb** [comment]
@rowild For what user role this is happening?
I guess this is happening because of validation. We just need to display the returned validation error message.

Try putting this in your register file and I think you will see validation returned message.

     @if ($errors->any())
       <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div>
     @endif

Let me know. I will fix this or you can create a pull request.

**Comment by rowild** [comment]
The fix you proposed has no effect whatsoever.
When clicking on register, the form is submitted via jquery (/resources/views/auth/register.blade.php, there is some js at the bottom). But this call only initiates a ajax reload, nothing else.
Where does the js goto? I would expect some form validation on the client side, but probably I am mistaken...
However, IMO this is not a blade problem, but an ajax problem...

**Comment by changeweb** [comment]
@rowild I just fixed this and made a pull request. It was a Javascript form selector issue. Check this
Validation working

![reg-err](https://user-images.githubusercontent.com/9896315/54624421-84cc2800-4a97-11e9-8a1c-5f30d3dc539b.png)

Registration working

![rgsaved](https://user-images.githubusercontent.com/9896315/54624514-b2b16c80-4a97-11e9-8398-0b4401c65c31.png)

**Comment by changeweb** [comment]
@rowild I will add a back to dashboard button as soon as possible

**Comment by changeweb** [comment]
I just added a button that leads back to the "Manage school" page

**Comment by rowild** [comment]
@changeweb Thank you for your quick fixes. I finally got it working.

May I suggest to use the bootstrap components for adding those buttons? From what I can see, "panel-header" and "panel-footer" are not in use. I'll provide an example to make my intention clearer.

**Comment by rowild** [comment]
This issue is closed. I open a new issue concerning the layout.
Thank you, @changeweb !
