### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by steadfastsnail** [changeweb/Unifiedtransform#149]
What shall I do?
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ProviderRepository.php line 208:

  Class 'Barryvdh\Debugbar\ServiceProvider' not found

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by changeweb** [comment]
Try removing these lines in `config/app.php`

```php
...
Barryvdh\Debugbar\ServiceProvider::class,
...
'Debugbar' => Barryvdh\Debugbar\Facade::class,
...
```

**Comment by changeweb** [comment]
My installation works. Follow the installation video from instruction page. Check your PHP setup.

![ut-issue](https://user-images.githubusercontent.com/9896315/58073761-494bf800-7bc5-11e9-88e8-813051abbd23.png)

**Comment by steadfastsnail** [comment]
![image](https://user-images.githubusercontent.com/49599745/58139547-c03ccb80-7c6d-11e9-846b-ad25e941e101.png)

A New Problem

**Comment by steadfastsnail** [comment]
![image](https://user-images.githubusercontent.com/49599745/58141114-ba96b400-7c74-11e9-83ee-3ed02bc0b849.png)

a new problem

**Comment by floviolleau** [comment]
If you want to seed, you need to be in development mode so run `composer install` and NOT `composer install --optimize-autoloader --no-dev` and in .env file APP_ENV=local.

It should solve your problem
