### ISSUE TITLE
Unable to login with master account on production

### ISSUE THREAD

**Issue by floviolleau** [changeweb/Unifiedtransform#162]
**Describe the bug**
If we install in production mode and we change 

**To Reproduce**
1. Clone the repository
`git clone https://github.com/changeweb/Unifiedtransform`
2. Copy the contents of the `.env.example` file to create `.env` in the same directory
3. Run `composer install --optimize-autoloader --no-dev`
4. Comment lines like mentionned in #149 to fix `Illuminate\Foundation\ComposerScripts::postAutoloadDump` error
4. Generate `APP_KEY` using `php artisan key:generate`
5. Edit the database connection configuration in `.env` file accordingly
6. Set the `APP_ENV` variable to `production`in the .env file
7. Migrate database with `php artisan migrate`
8. Point your domain name to the folder `public`. (I'm on shared server and I cannot start `php artisan server` due to the policy)
9. Create jquery min file that is missing in `public/js` folder by download it here https://code.jquery.com/jquery according to the version that is missing.
10. Reach the login page
11. Do optional speed up process:
To optimize site automatically with results in a 35%+ optimization, uncomment some lines from `Kernel.php` file and run `php artisan vendor:publish --provider="RenatoMarinho\LaravelPageSpeed\ServiceProvider"`.

**app/Http/Kernel.php**
```
    //\RenatoMarinho\LaravelPageSpeed\Middleware\InlineCss::class,
    //\RenatoMarinho\LaravelPageSpeed\Middleware\ElideAttributes::class,
    //\RenatoMarinho\LaravelPageSpeed\Middleware\InsertDNSPrefetch::class,
    //\RenatoMarinho\LaravelPageSpeed\Middleware\RemoveComments::class,
    //\RenatoMarinho\LaravelPageSpeed\Middleware\TrimUrls::class,
    //\RenatoMarinho\LaravelPageSpeed\Middleware\RemoveQuotes::class,
    //\RenatoMarinho\LaravelPageSpeed\Middleware\CollapseWhitespace::class,
```
12. To create a master account, go to `database/seeds/UsersTableSeeder.php` and change the `name`, the `email` and the `password` settings to your what you want. Leave the other settings (role, active, verified) unchanged!
12. Try to login

**Expected behavior**
Be able to login with master login/password info put in file `database/seeds/UsersTableSeeder.php`

**Desktop (please complete the following information):**
 - OS: Shared linux with Apache / mysql (server) / Windows 10 latest (client)
 - Browser: Firefox
 - Version: latest

**Comment by changeweb** [comment]
Did you seed database at least once? If not you need to run `php artisan db:seed` after migration.

**Comment by changeweb** [comment]
I've added some instructions regarding Production environment installation in Readme.md file.

Hope it helps.

**Comment by floviolleau** [comment]
Hi,

Thanks for your answer. It helps !
But I don't see where I need to comment that in the file. This code is not present:

In `database\seeds\UsersTableSeeder.php`:
```
...
//factory(App\User::class, 200)->create();
```

**Comment by changeweb** [comment]
Well, that line was changed to following:

```php

        factory(User::class, 10)->states('admin')->create();
        factory(User::class, 10)->states('accountant')->create();
        factory(User::class, 10)->states('librarian')->create();
        factory(User::class, 30)->states('teacher')->create();
        factory(User::class, 200)->states('student')->create();
```
I'm going to change that instruction in readme.md.

**Comment by floviolleau** [comment]
This what I did :).

I'm starting to do translation because I wanted to have it in French and all strings are hard coded in views :/

**Comment by changeweb** [comment]
@floviolleau others are also working with different languages support #133 . It would be helpful if you discuss or see the prefered way for translation support for this app. Thank you.

**Comment by JuanVqz** [comment]
@floviolleau good day! In your point 10, you don’t have JQuery because you should run `npm run dev` depending if you wanted for production or development and this command generates js that you needed, regards!

**Comment by floviolleau** [comment]
@JuanVqz: I did it (npm run production) but jquery load is hardcoded in the template `resources/views/welcome.blade.php`
Line 98 `<script src="{{asset('js/jquery-2.1.3.min.js')}}"></script>`
