### ISSUE TITLE
Can't generate autoloadf files - Composer

### ISSUE THREAD

**Issue by rippleytrigger** [changeweb/Unifiedtransform#163]
I'm trying to run the project on a laravel homestead enviroment and when I apply the "composer install" command, it says that it cannot generate the autoload files properly. Here is why: 

![image](https://user-images.githubusercontent.com/25210752/60686521-4e17f300-9e77-11e9-842d-d40891415338.png)

I need some help, please. I am not using a docker installation. Instead, I have clone the project on my developing enviroment.

**Comment by changeweb** [comment]
Try removing Laravel log viewer package from composer.json

**Comment by changeweb** [comment]
I've added some instructions regarding Production environment installation in Readme.md file.

Hope it helps.

**Comment by rippleytrigger** [comment]
I tried removing Laravel log viewer, but I keeps the same error on another package...

**Comment by rippleytrigger** [comment]
![image](https://user-images.githubusercontent.com/25210752/60761423-1d21f480-a016-11e9-9cb0-0c266b415bf3.png)

**Comment by changeweb** [comment]
@rippleytrigger I guess Vagrant may cause this PHP related problem. The error is showing a problem inside of a PHP Package not in this web app.

If you find out anything, let us know.

**Comment by rippleytrigger** [comment]
I manage to solve the problem by cloning the repo on another computer using ubuntu host OS. I think the problem should be on windows hosted laravel homestead, because when you use initially "composer install", it says that it cannot unzip some packages on the process.

**Comment by nkatagithub** [comment]
nope, there is no such directry as vendor/autoload, even in the github repo yet it is required by artisan on line 18
