### ISSUE TITLE
autoload.php file missing

### ISSUE THREAD

**Issue by aashu122** [changeweb/Unifiedtransform#164]
/home/ashu/school-management-system/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/ashu/school-management-system/artisan on line 18

**Comment by changeweb** [comment]
Give more details of the problem please.

**Comment by changeweb** [comment]
Your latest issue contains similar point. So I am closing this issue.

**Comment by aashu122** [comment]
I need some more information about the database connection procedure and
how does it create another one with my own requirements if I want to some
changes in the existing database.. So could you guide me with that I would
be very great full.
Thanks
