### ISSUE TITLE
operating sysytem related problem

### ISSUE THREAD

**Issue by aashu122** [changeweb/Unifiedtransform#166]
I am using ubuntu 16.04 and i have installed all prerequisites but i can not find autoload.php file.

showing that error,how can i fixed it??

PHP Warning:  require(/home/ashu/school-management-system/vendor/autoload.php): failed to open stream: No such file or directory in /home/ashu/school-management-system/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/home/ashu/school-management-system/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/ashu/school-management-system/artisan on line 18

**Comment by mykeels** [comment]
Have you run `composer install`?

**Comment by aashu122** [comment]
yess

**Comment by aashu122** [comment]
i have already worked at hyperledger composer

**Comment by aashu122** [comment]
composer version is 0.19.20

**Comment by mykeels** [comment]
When do you get this error?

**Comment by aashu122** [comment]
from 2 days

**Comment by aashu122** [comment]
After the installation of composer when i run (php artisan migrate)that commond.

**Comment by mykeels** [comment]
What action are you trying to do, that gives you this error?

Also, try `ls vendor` and see if it contains `autoload.php`

**Comment by aashu122** [comment]
I could not any such type of directory .

**Comment by aashu122** [comment]
Is there any possible way so i can fix this problm??

**Comment by aashu122** [comment]
anyone there??

**Comment by changeweb** [comment]
@aashu122 please don't use Issue section with a lot of short comments.

You can edit your existing comment. This will help others to understand your problem better.

**Comment by changeweb** [comment]
I've added some instructions regarding Production environment installation in Readme.md file.

Hope it helps.

**Comment by aashu122** [comment]
i have already installed hyperledger composer but still php artisan
key:generate could not run.

**Comment by aashu122** [comment]
can you please me proper instruction of installation of this erp

**Comment by aashu122** [comment]
bro can you plzz me your contact number i have lots of querys

**Comment by aashu122** [comment]
share*

**Comment by mykeels** [comment]
Looks like you don't have a `vendor` folder, and that's the problem. It should be generated, when you run `composer update` or `composer install`, within the project folder.

Could you run that, and take a screenshot of the output?

**Comment by nkatagithub** [comment]
thanks mykeels
