### ISSUE TITLE
Problems running on production

### ISSUE THREAD

**Issue by shreyaspapi** [changeweb/Unifiedtransform#167]
composer install --optimize-autoloader --no-dev

After doing composer install I am getting an error of carbon -

error -

  - Removing barryvdh/laravel-debugbar (v3.2.4)
Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ProviderRepository.php line 208:

  Class 'Barryvdh\Debugbar\ServiceProvider' not found

**Comment by shreyaspapi** [comment]
<img width="569" alt="Screenshot 2019-07-06 at 4 32 51 PM" src="https://user-images.githubusercontent.com/22324802/60755395-c2d06600-a00c-11e9-9651-5a258ba7c168.png">

**Comment by changeweb** [comment]
Duplicate of #149 #151 and #162 .

**Comment by changeweb** [comment]
I've added some instructions regarding Production environment installation in Readme.md file.

Hope it helps.

**Comment by shreyaspapi** [comment]
> I've added some instructions regarding Production environment installation in Readme.md file.
> 
> Hope it helps.

Thank you I will close the issue

**Comment by shreyaspapi** [comment]
After removing those things I am getting another error 

- Removing composer/semver (1.5.0)
 Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
PHP Fatal error:  Cannot use empty array elements in arrays in /var/www/html/Unifiedtransform/config/app.php on line 165
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255

**Comment by JuanVqz** [comment]
first you should copy `cp .env.example .env`

**Comment by shreyaspapi** [comment]
Already did all the steps and works fine in dev but not running on production even after deleting debugbar and lavaral log viewer

**Comment by shreyaspapi** [comment]
can anyone please help?

**Comment by JuanVqz** [comment]
@shreyaspapi share yours photos with errors

**Comment by norbybaru** [comment]
The issue here is because of the Service discovery and Service provider. There different ways to solve this depending on business case. I will suggest you should only register that Debuggar on local env.

I can create a PR if you can't get it right

**Comment by norbybaru** [comment]
@changeweb  maybe you should look into enabling styleCI for the project.

**Comment by changeweb** [comment]
@norbybaru ok. I'll have a look into styleCI. Thanks for the PR. I couldn't work around the issue.

**Comment by changeweb** [comment]
@shreyaspapi if this PR fixed your issue, let us know.

**Comment by Majidkadi** [comment]
I’ve had the same problem and I’ve fixed it by adding this line in public/.htaccess file:
RewriteBase ‘/‘

**Comment by shreyaspapi** [comment]
@Majidkadi Thank you, yes it did work at last.
