### ISSUE TITLE
ErrorException (E_NOTICE) Trying to get property of non-object

### ISSUE THREAD

**Issue by hg1233** [changeweb/Unifiedtransform#191]
Running without a Docker container, logged in with the default login details and the /home page looks like this:

![image](https://user-images.githubusercontent.com/45510654/62811057-32e47700-baf8-11e9-86e0-d61284e9551f.png)

New to this software, I need help getting this working.

Thanks in advance!

**Comment by changeweb** [comment]
@JuanVqz can you have a look please. This issue is related to #169 #188 .

Didn't your PR #169 already fix this? Dusk test need to be added in `.travis.yml` with proper set up.

Thanks.

**Comment by hg1233** [comment]
Could it potentially be a database issue? I did have a few errors when seeding the database.

**Comment by hg1233** [comment]
Managed to get around this by logging in using a master account, navigating to /masters and working from there.

**Comment by JuanVqz** [comment]
@changeweb I can check out tomorrow, but it works if you are master user redirects to /masters and if you are other user type redirects to /home.
I think this issue is when you push the navbars logo because redirect to /home or you try go direct to /home when you are master.

@hg1233Can you tell me how to you get the error?

**Comment by hg1233** [comment]
@changeweb Please check your inbox, I need some further assistance.

**Comment by hg1233** [comment]
@JuanVqz I simply loaded up the page for the first time, logged into the master account and it appeared. I had to get around it by navigating to /masters to reach the masters home page.
