### ISSUE TITLE
Can support Chinese language?

### ISSUE THREAD

**Issue by joneyhsiao** [changeweb/Unifiedtransform#194]
**Is your feature request related to a problem? Please describe.**
It's a good point if we can switch language there.

**Describe the solution you'd like**
Could you share the steps of how to support a new language?

**Comment by changeweb** [comment]
Copy **resources/lang/ES-MAX** folder and **resources/lang/ES-MAX.json** file. Then replace the Spanish words with Chinese ones.

**Comment by joneyhsiao** [comment]
> Copy **resources/lang/ES-MAX** folder and **resources/lang/ES-MAX.json** file. Create new folder and file naming **ZH-MAX**. Then replace the Spanish words with Chinese ones.

Thank you :), let me try.

**Comment by joneyhsiao** [comment]
also, have to update config/app.php as following:
`'locale' => 'ZH-MAX',`
