### ISSUE TITLE
Dashboard always shows 0 number of student and teacher.

### ISSUE THREAD

**Issue by joneyhsiao** [changeweb/Unifiedtransform#196]
After created student and teacher, the number of student and teacher in the Dashboard still showing 0.

**Comment by changeweb** [comment]
Please read the readme.md carefully. Dashboard is cached for 24hrs. If you want you can remove cached lines as instructed in readme.

**Comment by joneyhsiao** [comment]
Thank you very much. @changeweb very detailed in the readme regarding "good to know" section.
