### ISSUE TITLE
ErrorException (E_NOTICE) when user with master role request /home

### ISSUE THREAD

**Issue by stardigits** [changeweb/Unifiedtransform#208]
**Describe the bug**
ErrorException (E_NOTICE) happen when user with master role request /home

**To Reproduce**
1. Login as master
2. Request using url /home

**Expected behavior**
It should redirect to /masters (master homepage)

**Screenshots**
ErrorException (E_NOTICE)
Trying to get property 'id' of non-object

\app\Http\Controllers\HomeController.php
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
 
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $minutes = 1440;// 24 hours = 1440 minutes
        $school_id = \Auth::user()->school->id;

**Comment by changeweb** [comment]
Please see `Auth\LoginController.php -> public function redirectTo(){}`

**Comment by qq690712575** [comment]
I also met this problem for the first time.

**Comment by changeweb** [comment]
@qq690712575 @stardigits Can you please share any screenshots with error messages?

**Comment by stardigits** [comment]
@changeweb, Error description is clear. This error happens when 'master' entering url /home.
I did modify the `HomeController.php` as follows:

```
    public function index()
    {
      if (\Auth::user()->role != 'master') {
        $minutes = 1440;// 24 hours = 1440 minutes
        /* codes for non master users */
      } else {
        return redirect('/masters');
      }
    }
```

It's resolved.

**Comment by changeweb** [comment]
@stardigits It would be great if you make a PR.

**Comment by vyrral** [comment]
what function is used to promote student from one class/section/academic year to another, cant seem to find it
![54187741-6c2ca280-44d8-11e9-871a-51148b27c2b4](https://user-images.githubusercontent.com/76436041/124392638-ae540080-dcee-11eb-9455-1235d4a683d0.png)
