### ISSUE TITLE
Title text

### ISSUE THREAD

**Issue by alikhosravi** [changeweb/Unifiedtransform#216]
Hi there
Is it possible to change the Branding Image (Unifiedtransform) in this app ?
I Changed the app name but it doesn't work !

![main](https://user-images.githubusercontent.com/23376546/71365147-627db280-25b3-11ea-9399-8b309f46c124.jpg)

**Comment by changeweb** [comment]
This brand name is hard coded. BTW school's name will appear instead of Unifiedtransform after login.
