### ISSUE TITLE
total Students

### ISSUE THREAD

**Issue by alikhosravi** [changeweb/Unifiedtransform#218]
Hi there
$totalStudents don't work on home page I think.
I added one student in a school but $totalStudents is zero yet !!

**Comment by changeweb** [comment]
@alikhosravi the values are cached for 24hrs. You can change it. See the instruction in Readme.md file.

**Comment by alikhosravi** [comment]
@changeweb Thank you !!!!

**Comment by alikhosravi** [comment]
> @alikhosravi the values are cached for 24hrs. You can change it. See the instruction in Readme.md file.

**Comment by alikhosravi** [comment]
> @alikhosravi the values are cached for 24hrs. You can change it. See the instruction in Readme.md file.


Sorry I can't find any related instruction in the Readme.md !

**Comment by alikhosravi** [comment]
> @alikhosravi the values are cached for 24hrs. You can change it. See the instruction in Readme.md file.


Sorry I can't find any related instruction in the Readme.md !
