### ISSUE TITLE
Some bug reporting

### ISSUE THREAD

**Issue by shone83** [changeweb/Unifiedtransform#23]
Admin -> Profile>
``` "count(): Parameter must be an array or an object that implements Countable (View: D:\xampp\htdocs\school\resources\views\profile\user.blade.php)" ```

you can change:
```
count($user) > 0
```
to:
```
$user
```
in two if statement and that would work.

<hr>

Also, teacher can't be made. Error:

``` "count(): Parameter must be an array or an object that implements Countable" ```

<hr>

Then, when I made admin for school, register button is useless since I just click on upload pic and admin is made. Without pic upload I can't made admin which is lame.

<hr>

I have more, but this is enough for now...

**Comment by changeweb** [comment]
Can you share screenshots?

**Comment by shone83** [comment]
https://imgur.com/o7YbYaY
https://imgur.com/Huh80KC

**Comment by changeweb** [comment]
@shone83 I've made a fix about Teacher registration. Can you share the url or route of your Second problem about profile page? I can't recreate the situation here. Here are working screenshots about Teacher registration

![treg](https://user-images.githubusercontent.com/9896315/54679414-661a6f80-4b31-11e9-909f-a6872ea9ac87.png)

After register
![tres](https://user-images.githubusercontent.com/9896315/54679428-72063180-4b31-11e9-88e2-04a9be7dccae.png)

**Comment by shone83** [comment]
http://localhost/school/public/user/11916869

This is URL when I click on admin profile.

**Comment by changeweb** [comment]
@shone83 I've fixed and made pull request about Edit problem. But still failed to recreate the profile problem. Here are working screen shots

![ted](https://user-images.githubusercontent.com/9896315/54680727-d1b20c00-4b34-11e9-9f17-212b48dc3e50.png)
Profile page. See the url
![tpr](https://user-images.githubusercontent.com/9896315/54680788-f1e1cb00-4b34-11e9-82d2-8999ce5a08fb.png)

**Comment by shone83** [comment]
I removed ``` <option value="{{$user->department_id}}">{{$user->department->department_name}}</option> ``` but same error ``` Trying to get property 'id' of non-object (View: D:\xampp\htdocs\school\resources\views\profile\edit.blade.php) ```

**Comment by changeweb** [comment]
Did you remove the line inside foreach loop or outside of it? I removed the outside line. I guess you better create a department first or try. Or you can re download latest repository and try.

**Comment by shone83** [comment]
Outside line. I will try with new repository.

**Comment by shone83** [comment]
Same thing with new repository. Maybe it's problem because I didn't use factory, I only created one master and with master one admin. Then, with that admin in academic settings I made one department, one class and with that I created teacher.

**Comment by changeweb** [comment]
Can you try using this command `php artisan migrate:refresh --seed` and share with us if the problem exists?

**Comment by shone83** [comment]
With all factories or like I do until now?

**Comment by changeweb** [comment]
Follow the instructions on How to start in this repo

**Comment by shone83** [comment]
I try with all factories. Just edit teacher works, other problems still exist. Admin profile same error and when I click on teacher full name same error.

**Comment by changeweb** [comment]
Ok. Test other features. I will try to fix it by replacing `student_code` column in url using `user_id`.

BTW can you share screenshots about admin profile link and teacher full name pages?

**Comment by shone83** [comment]
Admin profile
https://imgur.com/bMitAtw

Teacher profile
https://imgur.com/OqJQvA5

**Comment by changeweb** [comment]
@shone83 In `UserController.php` page change the `create` function like this and share the output here

    public function create($student_code)
    {
      //$user = User::with('section')->where('code', Auth::user()->code)->where('student_code', $student_code)->first();
      $user = User::with('section','studentInfo')
                  ->where('student_code', $student_code)
                  ->first();
      dd($user);
      return view('profile.user', ['user' => $user]);
    }

**Comment by shone83** [comment]
```
User {#552 ▼
  #fillable: array:3 [▶]
  #hidden: array:2 [▶]
  #connection: "mysql"
  #table: null
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #withCount: []
  #perPage: 15
  +exists: true
  +wasRecentlyCreated: false
  #attributes: array:22 [▶]
  #original: array:22 [▶]
  #changes: []
  #casts: []
  #dates: []
  #dateFormat: null
  #appends: []
  #dispatchesEvents: []
  #observables: []
  #relations: array:2 [▶]
  #touches: []
  +timestamps: true
  #visible: []
  #guarded: array:1 [▶]
  #rememberTokenName: "remember_token"
  #accessToken: null
}
```

**Comment by shone83** [comment]
``` count(array($user)) > 0 ``` works...

**Comment by changeweb** [comment]
@shone83 I updated the repository with your fix. So I think this issue can be closed now.
