### ISSUE TITLE
Bug in impersonation makes any user possible to act even like a Master.

### ISSUE THREAD

**Issue by athulrajdr** [changeweb/Unifiedtransform#245]
**Describe the bug**
Impersonation feature does not filtering user list (while selecting the user) based on permission level of the user. This make an user possibly act like anyone. That includes admin from another school, teachers, and even the master.

**To Reproduce**
1. Login to the system
2. Click on 'impersonate' from menu
3. Select any user
4. See its possible to choose any user available on the system

**Expected behavior**
With the impersonation feature, a user could only be access to the user from the child roles.
That is
- A _**master**_ user can impersonate as all user from all roles (admin, teacher, student, librarian , accountant)

- An _**admin**_ user can impersonate as all users from the school (teacher, student, accountant, librarian).  but not as the _**master**_ user

**Screenshots**
- Logined as **admin**.  Selecting impersonate
![Screenshot (196)](https://user-images.githubusercontent.com/7678226/82246132-c2f5fd80-9961-11ea-96c1-59993aebc520.png)

- On the users list, you can see all the users from the system, Even the **master** user.

![Screenshot (197)](https://user-images.githubusercontent.com/7678226/82246292-08b2c600-9962-11ea-9628-f3fdae1421df.png)

- Choosing the **master** user is possible here. and now we can manage all schools, add admin to the school etc.
![Screenshot (199)](https://user-images.githubusercontent.com/7678226/82246501-6f37e400-9962-11ea-931e-8819b33db5e7.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Browser version [Version 81.0.4044.138]

**Comment by changeweb** [comment]
This feature is for development purpose only. Change your application Environment variable to 'production' from 'local'.

If you want to use impersonation for production, you can customize it.
