### ISSUE TITLE
 Certificate or diploma (pdf) to student

### ISSUE THREAD

**Issue by luisbonejo9807** [changeweb/Unifiedtransform#258]
A section to send diplomas or certificates to students for merits, contests and others, like notices but personal

**Comment by changeweb** [comment]
So you would like to send certificates to students by uploading certificate file same as uploading notice. Am I correct?

**Comment by luisbonejo9807** [comment]
Yes, is correct.

**Comment by changeweb** [comment]
This will be a nice feature. Thanks for the idea. I shall work to add this feature before next release.

**Comment by changeweb** [comment]
@luisbonejo9807 Added. See last 2 screenshots in readme.md.

**Comment by luisbonejo9807** [comment]
thank you very much :D

**Comment by Mahmood-Hussain** [comment]
@changeweb can we have a feature to dynamically generate certificates from the webpage itself without the need to upload manually?
