### ISSUE TITLE
Login Not run

### ISSUE THREAD

**Issue by LeDangIUH** [changeweb/Unifiedtransform#277]
I'm install success when I start php artisan serve ==> ok

But when I'm run: http://127.0.0.1:8000 ==> error.

Please help! thanks

<img width="1429" alt="Screen Shot 2020-11-25 at 7 08 57 PM" src="https://user-images.githubusercontent.com/3908468/100226282-17ea8000-2f52-11eb-8ff9-4b7063e3ea30.png">

<img width="838" alt="Screen Shot 2020-11-25 at 7 09 12 PM" src="https://user-images.githubusercontent.com/3908468/100226271-128d3580-2f52-11eb-962f-917095a2cb8e.png">

**Comment by williamdwiputra37** [comment]
I have the same problem as you, you can resolve it?

**Comment by williamdwiputra37** [comment]
@LeDangIUH have you solved the problem?

**Comment by LeDangIUH** [comment]
Not yet! I'm waiting support long time ago

**Comment by changeweb** [comment]
Try disabling PhpDebugBar.

**Comment by williamdwiputra37** [comment]
@changeweb it's work, thanks a lot man

**Comment by vicentimartins** [comment]
@changeweb did you think that this issue was solved? What about close it?

**Comment by changeweb** [comment]
@vicentimartins yes it is solved I think.
