### ISSUE TITLE
Route list error and solution 

### ISSUE THREAD

**Issue by shone83** [changeweb/Unifiedtransform#29]
``` php artisan route:list ``` is not working. Error:
```  Key path "file://C:\xampp\htdocs\musicSchoolDB\storage\oauth-private.key" does not exist or is not readable ```

You must enter command ``` php artisan passport:keys ``` to be able to use route list.

<hr>
@changeweb

Why master can't edit admins? Admin can't edit it's own profile either.

And, do you plane to add translate to other languages?

This is excellent software but I think it need a lot of work. I would love to help.

**Comment by changeweb** [comment]
@shone83 Good catch. `oauth` keys are not included because it should be different for each application. This is why this path is included in `.gitignore` file. 

I added **Passport** package to support **API**. If anyone don't want to include this package then just follow these steps

* Remove it from `composer.json` and run `composer update` and `composer dump-autoload`.

* And all classes that relies on passport must be edited as well. The most common classes are:

    * `app\User.php` model, remove the `HasApiToken` trait.
    * `app\Proiders\AuthServiceProvider`, remove `Passport::routes();` in your boot method.
    * In `config/auth.php`, change your driver option for `api` from `passport` to `api` authentication
    * Remove the **Passport Migrations** in database `migrations` table and run command `artisan migrate:refresh`

**Comment by changeweb** [comment]
And giving which role to edit admin's data would be good? What do you think? And why?

Your help will be appreciated.

**Comment by changeweb** [comment]
I've added Passport related instructions in readme.md with a pull request.

**Comment by shone83** [comment]
I think that master who create admin can also editing them and delete. Someone must be able to control them. Now you have situation that when admin is created no one can edit anything and what if master mad mistake in the project. Also, admin should have option to edit it's own profile, or just some parts. 

I know that deleting is a problem because that removes id, but it must be some kind of set admin to non active. That is must have.

I planing to translate whole thing to Serbian when all errors are removed. I hope that would be helpfull to motivate others to translate to other languages.

**Comment by changeweb** [comment]
@shone83 To make any user inactive we need to just set `active` field in `users` table to `0`. It would be great if you can build edit features for master and admin!

**Comment by norbybaru** [comment]
I agree with @shone83 I believe `master` should be able to manage school `admin` and school `admin` should able to update their details without being able to change their role or School

**Comment by changeweb** [comment]
@shone83 @norbybaru Now you can activate and deactivate Admin from Master account from view admin page

**Comment by shone83** [comment]
This topic can be used until all errors are corrected. 

The further I noticed is that the count in the dashboard of professors and students does not work.

Also in Admin - Profile there is empty filed for nationality and religion. That fields not exist in form when master creating the admin. I do not think it's necessary.

**Comment by changeweb** [comment]
@shone83 counts in Dashboard are Cached for 24hrs. It should be updated after 24hrs or if you delete cache files.

See in `HomeController.php`

**Comment by shone83** [comment]
Yes, I see. These days I will test more and place here if I notice something if that's ok.

**Comment by shone83** [comment]
When I run ``` composer install ``` this error appear:

```
It is unsafe to run Dusk in production.
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

Also, some columns in users migration is not nullable. It says:

```
 Integrity constraint violation: 1048 Column 'school_id' cannot be null
```

you must add this ``` ->unsigned()->nullable() ``` to accept null values. That is also for code and section_id columns.

**Comment by changeweb** [comment]
@shone83 in Laravel's document also mentioned that running Dusk is not safe for production environment. To fix this run `composer install --no-dev`.

Can you make a pull request on user migration error?

**Comment by shone83** [comment]
As soon as to realize how to do that. I never done it before.

**Comment by changeweb** [comment]
@shone83 there is a first time for everything :smiley: .Try it!

**Comment by ShekhSaifuddin007** [comment]
Great Work...

**Comment by ShekhSaifuddin007** [comment]
I got another error that `Class 'Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider' not found` @changeweb how can i fix this.

**Comment by changeweb** [comment]
@ShekhSaifuddin007 Try this solution. If this work let me know. Then I will add this in Readme.md section as instructions.

**Comment by changeweb** [comment]
@ShekhSaifuddin007 [Check this link](https://github.com/rap2hpoutre/laravel-log-viewer/issues/53#issuecomment-173856677)

> The class keyword was added in PHP 5.5, so it will not work with your version. You should replace this (in your config/app.php in providers section):
 > `Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider::class,`
 by this:
 > `'\Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider',`
> And it will work. Source:
> http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class

**Comment by ShekhSaifuddin007** [comment]
@changeweb 
I got the solution for this error `Class 'Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider' not found` by run this command `composer require rap2hpoutre/laravel-log-viewer` i got this from [https://github.com/rap2hpoutre/laravel-log-viewer](url)

**Comment by ShekhSaifuddin007** [comment]
@changeweb Btw I sent you an email if you check it out.
