### ISSUE TITLE
Is your email Up?

### ISSUE THREAD

**Issue by amammad** [changeweb/Unifiedtransform#317]
Hey dear changeweb team.
can you just check that your email with address `robinmilfor870@gmail.com` is working or not ?
If it is Up already, can you tell me receive any message from Huntr.dev or not?
with regards, Amammad.

**Comment by changeweb** [comment]
It works. Sorry, I have missed your email. I checked the vulnerability. Do you have any suggestion about the fix?

**Comment by amammad** [comment]
I want to send you the fix suggestions but get this error

Address not found
Your message wasn't delivered to robinmilfor870@gmail.com because the address couldn't be found, or is unable to receive mail.
LEARN MORE

**Comment by changeweb** [comment]
Oh, you made a mistake. It is **robinmilford870@gmail.com** not **robinmilfor870@gmail.com**. You missed **d**.

**Comment by changeweb** [comment]
Hi amammad,
I have added a patch for this issue. Please check and let me know if this
is working.

Regards,
Hasib Mahmud

**Comment by amammad** [comment]
Hey man how are you today, I hope for you to be fine … 
I'm so sorry, yesterday I had problem and I can't answer your last question in email.
Yah now this is good.
also look at these reports that already have same issue in mentioned endpoints 
https://huntr.dev/bounties/accbf214-2183-461c-856d-f57c239bac45/
https://huntr.dev/bounties/15de56d1-69f2-43e7-be83-1706dd3553b6/
https://huntr.dev/bounties/a879969e-fcab-4d00-87e2-43f33c425fc7/
https://huntr.dev/bounties/9fe128e3-f5e7-4041-8655-c8991ab07baa/

**Comment by changeweb** [comment]
No problem. Thanks for pointing out other issues. I will patch them as well.

**Comment by changeweb** [comment]
@amammad I have pushed a commit regarding the fix of these issues. Please check and let me know if it is working.

**Comment by amammad** [comment]
Yah I saw them, just make the other GET requests to POST like /event endpoint.

**Comment by changeweb** [comment]
Today's commit is about those changes.

**Comment by amammad** [comment]
OK, I comment on the lines of commit that clarify what I mean.

**Comment by amammad** [comment]
Hey man can you just validate my reports in this time?
I said this as maybe we forget to do this.
thanks again.

**Comment by amammad** [comment]
Hey man, how are you today?
can I ask the Huntr.dev panel for you how looks like?
because I report 5 vulnerabilities and I think you just able to see 2 of them.

**Comment by amammad** [comment]
Hey man How are you these days ?
can I ask you to look at my new report ?
