### ISSUE TITLE
I am having errors running it on Docker, see the errors below

### ISSUE THREAD

**Issue by patelmohammed357** [changeweb/Unifiedtransform#319]
Creating unifiedtransform_composer_run ... done
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 150 installs, 0 updates, 0 removals

                                                                 
  [RuntimeException]                                             
  /var/www/html/vendor does not exist and could not be created.  
                                                                 

install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...

Creating unifiedtransform_artisan_run ... done

Warning: require(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/artisan on line 18

Fatal error: require(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/artisan on line 18

**Comment by handhikadj** [comment]
try to run `sudo chmod -R 777 .` from Unifiedtransform root directory

**Comment by patelmohammed357** [comment]
Thanks it worked, but I can’t login in it says “These credentials do not
much our records.

I’m using the email: ***@***.***

Password: secret

**Comment by patelmohammed357** [comment]
It’s not working I’m using the logins details in  UsersTableSeeder.php

**Comment by handhikadj** [comment]
give me screenshot, please

**Comment by patelmohammed357** [comment]
[image: Capture1.PNG]
Here is the screenshot of the errors

**Comment by patelmohammed357** [comment]
[image: Capture.PNG]

**Comment by handhikadj** [comment]
WTH is this?

![image](https://user-images.githubusercontent.com/22522638/130315963-1bf5be41-7964-430d-9168-d1cc1073efcc.png)

**Comment by patelmohammed357** [comment]
![Capture](https://user-images.githubusercontent.com/89032410/130316149-5ca7d00f-7a59-480b-bb11-ffbe76baf72c.PNG)

**Comment by handhikadj** [comment]
did you `migrate`?

**Comment by patelmohammed357** [comment]
yes

**Comment by patelmohammed357** [comment]
![Capture2](https://user-images.githubusercontent.com/89032410/130316696-3458d77c-ba68-4115-b742-d49a92f5e831.PNG)

**Comment by handhikadj** [comment]
the password was `secret` right?

**Comment by patelmohammed357** [comment]
yes

**Comment by handhikadj** [comment]
how do you run the `migrate` ?
it should be `./dev artisan migrate` if you use the utility script

**Comment by patelmohammed357** [comment]
Already created .env file. And i run ./docker-install.sh
And it did everything. Do i need run anything on my command terminal or
anything i need to configure?

**Comment by patelmohammed357** [comment]
and i want to use it for production

**Comment by changeweb** [comment]
@patelmohammed357 You need to Seed with migrate at least the UserSeeder to register Master account. Use `--seed` flag with migrate command.

**Comment by patelmohammed357** [comment]
Thank you, can you please make it a bit easy if possible? Like as in how i
can use - -seed flag with migrate command?

**Comment by handhikadj** [comment]
jeez. it's laravel specific not the docker per se
please learn the basic docker and laravel

**Comment by patelmohammed357** [comment]
Already know some basics of docker and laravel since its my favorite. I was just confused since your code and you already know everything what is going thru

**Comment by patelmohammed357** [comment]
Thank you, I am getting that when i run php artisan migrate:refresh --seed

![Capture3](https://user-images.githubusercontent.com/89032410/130322109-573fc6e3-7cf4-49b9-9248-8dbfe28ed3dc.PNG)

**Comment by changeweb** [comment]
@patelmohammed357 Try running `./dev artisan migrate:refresh --seed`.

**Comment by handhikadj** [comment]
> Already know some basics of docker and laravel since its my favorite. I was just confused since your code and you already know everything what is going thru

so why did you `migrate` on the host machine instead of in the container

**Comment by patelmohammed357** [comment]
Thanks it works with no issues!!!!
