### ISSUE TITLE
Does UT only work with docker? Where is the tutorial without docker?

### ISSUE THREAD

**Issue by edersongs2905** [changeweb/Unifiedtransform#384]
I have tried to install Unifiedtransform (UT) but with no success. I tried with and without docker.
If there are two ways to install, with and withou docker, we could have two tutorials.
My mom has a small school and we were thinking about using UT.
I´m from Brazil.

Is there any way to contact someone and get some help?

Thanks!

**Comment by gerpollo2000** [comment]
Hi, do you need to install it in a local server, AWS or in a VPS?

**Comment by ederson2905** [comment]
Hi, in a VPS with Ubuntu server 22.04.

**Comment by emerson-pj** [comment]
> Hi, in a VPS with Ubuntu server 22.04.

Hello,
I am also looking for academic management systems.
I'm also from Brazil.
And also I can only use Ubuntu.

**Comment by edersongs2905** [comment]
@emerson-pj, good to see someone from Brazil.

I tried to install using docker is it´s not working for me.

I tried without docker. I installed php8.2, nginx, mysql and even apache2.
1-I cloned the repository with  "git clone https://github.com/changeweb/Unifiedtransform.git"
2-Created the folder ~/Unifiedtransform/storage/app/purify
3-Ran cp .env.example .env.
4-Ran docker-compose up -d.
5-Ran docker exec -it db sh. Inside the shell, ran:
mysql -u root -p


But I get this error:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by edersongs2905** [comment]
> ![image](https://user-images.githubusercontent.com/39161333/230109322-10ba29bf-d37c-490e-945c-aaf11a68c8ae.png) @edersongs2905 The readme file says you should use any other 'DB_USERNAME' instead of 'root' You can create your preferred user but don't use root.

I get the same error:
ERROR 1045 (28000): Access denied for user 'unifiedtransform'@'localhost' (using password: YES)

The DB_USERNAME is unifiedtransform

**Comment by akoruji** [comment]
Ensure you grant privileges to the user you created.
Also use 127.0.0.1 in your .env file for DB host

**Comment by yungifez** [comment]
UT works without docker

Clone it

Run composer install
Php artisan migrate 
Php artisan db:seed
Php artisan key:generate

**Comment by yungifez** [comment]
Dont forget to modufy your env

**Comment by changeweb** [comment]
> @emerson-pj, good to see someone from Brazil.
> 
> I tried to install using docker is it´s not working for me.
> 
> I tried without docker. I installed php8.2, nginx, mysql and even apache2. 1-I cloned the repository with "git clone https://github.com/changeweb/Unifiedtransform.git" 2-Created the folder ~/Unifiedtransform/storage/app/purify 3-Ran cp .env.example .env. 4-Ran docker-compose up -d. 5-Ran docker exec -it db sh. Inside the shell, ran: mysql -u root -p
> 
> I put my passwords in .env and docker-compose.yml files
> 
> But I get this error: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

Did you grant privileges to the user? Besides, you can setup your own mysql database and connect to it. You do not necessarily have to use Docker setup.

**Comment by changeweb** [comment]
> > ![image](https://user-images.githubusercontent.com/39161333/230109322-10ba29bf-d37c-490e-945c-aaf11a68c8ae.png) @edersongs2905 The readme file says you should use any other 'DB_USERNAME' instead of 'root' You can create your preferred user but don't use root.
> 
> Is to create another user to mysql or to the system? If it´s mysql, how do I do this? If possible, tell me the privileges I have to create also (command).
> 
> I never used mysql. I´m trying to test something first and see how it works, if Unifiedtransform can be in Portuguese too and etc.
> 
> Thanks for your patience!

The privileges are documented in the README.md file in project root. Yes, Unifiedtransform can be in Portuguese. You have to create a translation file for it and set the default language in config.

**Comment by edersongs2905** [comment]
@emerson-pj, as you´re in Brazil, we can translate it together, after it works. What do you think about?
@emerson-pj, como vc está no Brasil, podemos trazudir juntos, após ele funcionar. O que acha?

**Comment by emerson-pj** [comment]
> @emerson-pj, as you´re in Brazil, we can translate it together, after it works. What do you think about? @emerson-pj, como vc está no Brasil, podemos trazudir juntos, após ele funcionar. O que acha?

@edersongs2905 Ok, I already translated some systems, maybe I can help.
Call me on my facebook, there's the link here on my github profile.

**Comment by edersongs2905** [comment]
@emerson-pj , I sent you a message through Facebook.
