### ISSUE TITLE
Help needed for V1.

### ISSUE THREAD

**Issue by Akshay-Arjun** [changeweb/Unifiedtransform#387]
Followed the steps and when i run

docker-compose run --rm composer install , the following error throws up.
``` In collection. Php line 11: during inheritance of arrayaccess: uncaught errorexception: return type of illuminate\support\collection: : offsetexists($key) should either be compatible with arrayaccess: : offsetexists(mixed $offset): bool, or the #[\returntypewillchange] attrib ute should be used to temporarily suppress the notice in /var/www/html/vendor/laravel/framework/src/illuminate/support/col lection. Php:1349 

stack trace: 

#0 /var/www/html/vendor/laravel/framework/src/illuminate/support/collection. Php(11): illuminate\foundation\bootstrap\handl eexceptions->handleerror(8192, 'return type of ... ', '/var/www/html/v... ', 1349) 
#1 /var/www/html/vendor/composer/classloader. Php(576): include('/var/www/html/v... ') 
#2 /var/www/html/vendor/composer/classloader. Php(4judgzvrmfdwruuwy3tojatsenwjn54lkcnkbprzduhzi5vsephfuckjnxrl2gjknrsqtcoruredagrwsqvvcjzbryftlrnydmt1a1bozvvendor/laravel/framework/src/illuminate/support/helpers. Php(110): composer\autoload\classloader->loadclas s('illuminate\\supp... ') 
#4 /var/www/html/vendor/laravel/framework/src/illuminate/foundation/packagemanifest. Php(130): collect(array)
#5 /var/www/html/vendor/laravel/framework/src/illuminate/foundation/packagemanifest. Php(106): illuminate\foundation\packag emanifest->build()
#6 /var/www/html/vendor/laravel/framework/src/illuminate/foundation/packagemanifest. Php(89): illuminate\foundation\package manifest->getmanifest() 
#7 /var/www/html/vendor/laravel/framework/src/illuminate/foundation/packagemanifest. Php(78): illuminate\foundation\package manifest->config('aliases') 
#8 /var/www/html/vendor/laravel/framework/src/illuminate/foundation/bootstrap/registerfacades. Php(26): illuminate\foundati on\packagemanifest->aliases()
#9 /var/www/html/vendor/laravel/framework/src/illuminate/foundation/application. Php(230): illuminate\foundation\bootstrap\ registerfacades->bootstrap(object(illuminate\foundation\application)) 
#10 /var/www/html/vendor/laravel/framework/src/illuminate/foundation/console/kernel. Php(310): illuminate\foundation\applic ation->bootstrapwith(array) 
#11 /var/www/html/vendor/laravel/framework/src/illuminate/foundation/console/kernel. Php(127): illuminate\foundation\consol e\kernel->bootstrap()
#12 /var/www/html/artisan(35): illuminate\foundation\console\kernel->handle(object(symfony\component\console\input\argvinp ut), object(symfony\component\console\output\consoleoutput)) #13 {main} script @php artisan package: discover handling the post-autoload-dump event returned with error code 255 ```

**Comment by yungifez** [comment]
What is your php version

**Comment by Akshay-Arjun** [comment]
Its 7.4.33 .
More info :
-> I am on Windows and Linux, and I am getting the same errors on both machines.
-> Copied the .env.example to .env
-> Ran `docker-compose up -d `
-> Ran `docker-compose run --rm composer install`
Got the above errors.

**Comment by yungifez** [comment]
Ill check the docker compose file for php version

But consider setting it up without docker for testingvas im busy at the moment

**Comment by yungifez** [comment]
Ill check the docker compose file for php version

But consider setting it up without docker for testingvas im busy at the moment

**Comment by Akshay-Arjun** [comment]
I have run both of them out of the container on cmd/terminal on windows/linux just like i ran `docker-compose up d`. Sorry i'm newbie :)

**Comment by yungifez** [comment]
Try running your composer install inside the container itself

**Comment by Akshay-Arjun** [comment]
How can i do that ? :(

**Comment by kenzinotech** [comment]
Try setting up a UnifiedTransform project on Windows 10 without Docker:

https://mykeels.medium.com/unifiedtransform-getting-started-in-2021-286842edacad

I am using this method and it is running fine.

**Comment by yungifez** [comment]
> Try setting up a UnifiedTransform project on Windows 10 without Docker:
> 
> https://mykeels.medium.com/unifiedtransform-getting-started-in-2021-286842edacad
> 
> I am using this method and it is running fine.

I mentioned that but i got no response on that from op

**Comment by yungifez** [comment]
> How can i do that ? :(.
> Version 2 works well , but I need version 1 and I couldn't make it run. Even tried with docker-install.sh file. 

That exception looks like a php exception 

You are most probably running the commands outside the container

Since this project doesn't use sail, i cannot tell which of the services the prohect is mounted on without looking at the dicker compose file

Could you take a picture of your docker desktop?

**Comment by Akshay-Arjun** [comment]
![image](https://github.com/changeweb/Unifiedtransform/assets/68991993/959a29f5-be5d-4025-8ec6-c7b65e6ade3b)
Tried to start composer and artisan but they are exiting and stopping.

**Comment by yungifez** [comment]
Click on the php service, then switch over to the terminal

Run pwd command and post the results

Also try running compoaer install from there

**Comment by yungifez** [comment]
Good, we are making progress

As a root user, or if sudo doesn't throw an error, run 


(Sudo) apt-get install php-7.4-common

Also, run it with zip instead of common at the end

**Comment by Akshay-Arjun** [comment]
> (Sudo) apt-get install php-7.4-common
Should i run it in my docker php terminal? 
```
/var/www/html # apt-get install php-7.4-common
/bin/sh: apt-get: not found
/var/www/html #
```

**Comment by yungifez** [comment]
You need to find how to install the zip extension of php in that distro

A bit of googling would help
