### ISSUE TITLE
Blood Group?

### ISSUE THREAD

**Issue by rowild** [changeweb/Unifiedtransform#4]
I would like to know, if there is any use case in any school in the world, that requires a pupil or teacher or parent to give in their blood type? I am from Austria, and I never heard of such a thing.

(I know that other school systems like eduella do have a similar field...)

**Comment by changeweb** [comment]
I tried to add as many fields as possible to get much more options. You can obviously mute this field.

**Comment by changeweb** [comment]
@aminraeisi That's a good point. Lets make the fields customizable by admin.
