### ISSUE TITLE
Moving Request validation to FormRequest

### ISSUE THREAD

**Issue by norbybaru** [changeweb/Unifiedtransform#44]
Currently Controllers are very large and doing lot stuff which shouldn't be there. I would like to move request validation from `Controllers` to `FormRequest`. I will first do it on the `UserController` as an example.

This way Controller will do what its suppose to be doing with the data and let the FormRequest validate those data.

**Comment by changeweb** [comment]
@norbybaru I need to review your changes before accepting. Thanks for your contribution

**Comment by norbybaru** [comment]
@changeweb thanks for checking it out. Since you were happy with the changes and it didn't break anything I will do another controller and create a PR. I don't want to do all of them at once in case it just break something since there isn't lot of test coverage to test once changes are made. It will make your review easier for now if I do small chunk
