### ISSUE TITLE
Migrate to Bootstrap 4 (plan for v5)

### ISSUE THREAD

**Issue by thehitechpanky** [changeweb/Unifiedtransform#49]
Its based on Bootstrap 3, which is quite old now. You should consider moving to bootstrap 4, and plan for Bootstrap 5 as 2019 is the planned year for its release.

**Comment by changeweb** [comment]
@thehitechpanky you are right but unfortunately I don't have enough time to do it now. I've been working on improving other issues of the software. It would be great if you contribute with a stable migration from bootstrap 3 to 4.
