### ISSUE TITLE
How to start with the app?

### ISSUE THREAD

**Issue by rowild** [changeweb/Unifiedtransform#5]
I created a user with name, email and password using artisan tinker. Then, after login, I get this error: "Trying to get property of non-object". It seems the systems wants to know, which school the user belongs to. But since there is no data, nothing can be found.

How can I initialize the system correctly?

**Comment by shankargiri** [comment]
You could change `UsersTableSeeder.php` to : 
1 . `\App\User::updateOrCreate([ 'email' => 'youremail@example.com'], [
            'name' => "Your name,
            'password' => bcrypt('secret'),
            'role' => 'master',
            'active' => 1,
            'verified' => 1,
        ]);`

2. `php artisan db:seed`, you should be able to login with the above email and view those fake seeded data. 

I think its a good start, but has many errors.

**Comment by changeweb** [comment]
I will a add a Installation Documentation as soon as possible

**Comment by changeweb** [comment]
@rowild I've added a basic installation guide. Hope it helps.
