### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by znsstudio** [changeweb/Unifiedtransform#52]
It will be much easier if you can dockerize and make it seamless

**Comment by changeweb** [comment]
@znsstudio I know but unfortunately I don't have any working experience with any container system like Docker. It would be great if you can help with your Docker experience.

**Comment by znsstudio** [comment]
ok! I will try to work on that and make it work

**Comment by changeweb** [comment]
Setting up this application getting complicated for different versions of PHP and composer packages for different users. Wrapping the application with Docker may remove this complexity by creating a layer of abstraction.

So if you can help on this it will be great.
