### ISSUE TITLE
Undefined variable: school_id

### ISSUE THREAD

**Issue by iamrahman** [changeweb/Unifiedtransform#54]
When I login As a School Admin I got this error

**Comment by changeweb** [comment]
@iamrahman I forgot to call this `$school_id` inside callback function. Now it's fixed.

**Comment by iamrahman** [comment]
(1/1) ErrorExceptionUndefined variable: school_id
--
in HomeController.php line 66
at HandleExceptions->handleError(8, 'Undefined variable: school_id', '/home/user/Documents/Unifiedtransform/app/Http/Controllers/HomeController.php', 66,array())in HomeController.php line 66

@changeweb Still I am getting the error. I have pulled the code

**Comment by iamrahman** [comment]
I have fixed the Issue. I think you forget to write 
use($school_id)
at line:65, At: Unifiedtransform/app/Http/Controllers/HomeController.php.

**Comment by changeweb** [comment]
I fixed missing line at 65.
