### ISSUE TITLE
/login is Loading some loaders 

### ISSUE THREAD

**Issue by anuragyadav8949** [changeweb/Unifiedtransform#59]
http://127.0.0.1:8000/login as am hitting this url its loading some loaders, no page is getting load any issues??

**Comment by changeweb** [comment]
We need details of your situation

**Comment by pedroroccon** [comment]
Same issue for me. When I try to access the /login route, the page loads just a loader... A Javascript error is thrown.

`Uncaught SyntaxError: Unexpected token >`
`Uncaught ReferenceError: PhpDebugBar is not defined
    at login:4`
`Uncaught TypeError: $ is not a function
    at HTMLDocument.<anonymous> (login:4)
    at j (jquery-2.1.3.min.js:3)
    at Object.fireWith [as resolveWith] (jquery-2.1.3.min.js:3)
    at Function.ready (jquery-2.1.3.min.js:3)
    at HTMLDocument.I (jquery-2.1.3.min.js:3)`
`Uncaught TypeError: $ is not a function
    at login:4
    at dispatch (jquery-2.1.3.min.js:7)
    at r.handle (jquery-2.1.3.min.js:7)`

![image](https://user-images.githubusercontent.com/5197067/55656143-6b7fe700-57cc-11e9-9dac-d7e74d66cfc4.png)

**Comment by changeweb** [comment]
Can you try reinstalling the app with removing `barryvdh/laravel-debugbar` from your composer.json

**Comment by changeweb** [comment]
@anuragyadav8949 @pedroroccon I've made some recent changes about this issue and made a PR. Check and let me know if this fix your problem.

**Comment by pedroroccon** [comment]
> Can you try reinstalling the app with removing `barryvdh/laravel-debugbar` from your composer.json

That's fixed the problem

**Comment by anuragyadav8949** [comment]
> @anuragyadav8949 @pedroroccon I've made some recent changes about this issue and made a PR. Check and let me know if this fix your problem.

Thanks Buddy Its Working,If its possible can u tell me the mistake/changes u have made which was causing this error,that will be helpfull for me too :)

**Comment by changeweb** [comment]
@anuragyadav8949 I used a Laravel package for page speed. This package may not work properly in everybody's setup. That's why I comment the code lines from `Kernel.php`. See README.md about this change.

**Comment by dipakagile** [comment]
> @anuragyadav8949 @pedroroccon I've made some recent changes about this issue and made a PR. Check and let me know if this fix your problem.

I have a same problem . i had reinstalled that package but still face same issue

**Comment by mykeels** [comment]
Adding
```
Route::get( '/_debugbar/assets/stylesheets', '\Barryvdh\Debugbar\Controllers\AssetController@css' );
Route::get( '/_debugbar/assets/javascript', '\Barryvdh\Debugbar\Controllers\AssetController@js' );
```

to the `routes/web.php` file fixed the `PhpDebugBar is not defined` problem for me.

Should there be a PR for this?

**Comment by dipakagile** [comment]
> Route::get( '/_debugbar/assets/stylesheets', '\Barryvdh\Debugbar\Controllers\AssetController@css' );
> Route::get( '/_debugbar/assets/javascript', '\Barryvdh\Debugbar\Controllers\AssetController@js' );

yes its worked thnaks bro

**Comment by musman92** [comment]
problem still exist
