### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by zainqayyum954** [changeweb/Unifiedtransform#66]
When i login using teach account and goto Studens->View Attendance.
in AttendanceController.php on line# 60

**Comment by changeweb** [comment]
Give full error message with screenshots

**Comment by zainqayyum954** [comment]
![Capture](https://user-images.githubusercontent.com/38277697/55714394-0e727400-5a0c-11e9-8393-7f17048343b5.PNG)

**Comment by changeweb** [comment]
Write the following code and share the output here:

    $exam = .......
    dd($exam);
    if(count($exam) == 1)

**Comment by changeweb** [comment]
@zainqayyum954  This is probably happening because of different PHP versions of us. [See this post](https://stackoverflow.com/q/48343557/2429040)

I will try to find a version independent solution. Thanks for pointing out this problem

**Comment by zainqayyum954** [comment]
solved
Thanks

**Comment by changeweb** [comment]
@zainqayyum954 What was the reason behind the problem? And how did you fixed it?
I'll also push an update regarding this fix. So keep your cloned repository up to date with master.

**Comment by zainqayyum954** [comment]
using this..
dd($exam);
