### ISSUE TITLE
Bulk Importer

### ISSUE THREAD

**Issue by arifpavel** [changeweb/Unifiedtransform#71]
**Is your feature request related to a problem? Please describe.**
Most of the schools already have existing students,teachers,etc. In addition to the add student/add teacher etc options they should get an option to register/add/import thier exisiting students/teachers. I think I don't have to describe the problem in detail as You might know how much important it is :)

**Describe the solution you'd like**
Let's have an option to upload excell or csv file to register/import the students,teachers etc.

**Describe alternatives you've considered**
Or admin can register student with minimum options like name/class/section/mail & password then students can fill up other (non-required) information on thier own.

**Additional context**
But either of the solution bulk uploader is a really necessary feature I believe.

**Comment by changeweb** [comment]
@arifpavel I've a plan to add option of uploading excel or csv to bulk upload but for this a standard file format is needed according to database table fields. Let this software a bit mature and I'll have to make a parser for this. It would be great if you can contribute.

**Comment by changeweb** [comment]
@arifpavel Import/Export from/to Excel is added. Update to latest repository.

**Comment by q2dg** [comment]
Great! Import/Export from/to csv files could be possible too?

Note there's also a very popular open-source timetable generator called FET (https://lalescu.ro/liviu/fet) which generates its results in XML, but importing this would be a lot of work.
