### ISSUE TITLE
A way to view newly created School Admin

### ISSUE THREAD

**Issue by mykeels** [changeweb/Unifiedtransform#72]
**Is your feature request related to a problem? Please describe.**
When I create a school's admin, I get a notification saying the admin has been saved, but I don't see my newly created admin. 

**Describe the solution you'd like**
Perhaps, include a link to open the newly created school admin in a new tab in the "Saved" notification.

**Describe alternatives you've considered**
I've considered redirecting the user to the "View Admins" `school/admin-list/2` page, but a user might be interested in entering multiple admins one after the other.

> Also, this is really amazing work you're doing!

**Comment by changeweb** [comment]
You can view all your created Admin account by clicking **View Admins** link next to **Create Admin** after login from Master account.

**Comment by mykeels** [comment]
I know you can. I'm proposing this feature for better usability.

**Comment by changeweb** [comment]
@mykeels I considered the alternative you suggested and that's why master don't redirected after creating an Admin. But your solution of including a link to open the newly created school admin in a new tab in the "Saved" notification is good. I would definitely try to add it but if you can help it would be great :-)

**Comment by anishojha** [comment]
@mykeels @changeweb Hi, I have updated the code to display a link to view admins in success message, please check the screenshot. Let me know if all good I will create a pull request.

![image](https://user-images.githubusercontent.com/24322181/55901630-53063700-5be7-11e9-8549-943eef5d532b.png)
