### ISSUE TITLE
Invite mail to newly added user

### ISSUE THREAD

**Issue by mykeels** [changeweb/Unifiedtransform#73]
**Is your feature request related to a problem? Please describe.**
I added a school admin, and expected the admin to get an email.

**Describe the solution you'd like**
Send a mail, inviting the user to the system.

**Comment by changeweb** [comment]
@mykeels Yes this would be nice. But I'm focusing on eliminating bugs before working on any new feature right now. It would be great if you can help in this regard :-)

**Comment by mykeels** [comment]
Could you point me to the part of the code where I'd need to work with to send the mail after adding a user?

Also, there are any code paradigms?

**Comment by changeweb** [comment]
You may use Laravel Event and Listener. After creating an user in `UserController.php`, Dispatch an event about mail. [Events](https://laravel.com/docs/5.5/events) and [Mail](https://laravel.com/docs/5.5/mail#sending-mail). And there is Mail configuration in `.env` file.

**Comment by anishojha** [comment]
@changeweb @mykeels I have added functionality to send welcome email to admin on registration, It's not sending email from localhost, but I have checked its by logging the mail, and its working fine for me, but I want to make sure its sending actual email, I have created a PR #82  for this, please check it on your side and let me know your reviews.

**Comment by changeweb** [comment]
#82 We can add this invitation mail system for other users' registration also. What do you think?

**Comment by anishojha** [comment]
@changeweb  Yes, just add only one line for all user store function
`event(new UserRegistered($tb));` replace `$tb` with the registered user's object.

**Comment by changeweb** [comment]
@anishojha I think to send actual mail we need to run a mail server or use third party mail servers like **Mailgun, SparkPost, Amazon SES, etc.**  and modify `config/mail.php` and `config/services.php` configuration file.

[Mailgun Driver](https://laravel.com/docs/5.5/mail#introduction)

**Comment by anishojha** [comment]
@changeweb to send mail
do some changes on .env
```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=YOUR_GMAIL_ADDRESS_HERE
MAIL_PASSWORD=YOUR_GMAIL_PASSWORD_HERE
MAIL_ENCRYPTION=tls
```

**Comment by changeweb** [comment]
@anishojha I will try it and let you know.

**Comment by changeweb** [comment]
I used Mailtrap.io API. It worked. I'm merging the PR.
But mail template need to be improved.

**Comment by anishojha** [comment]
okay, we can use [Markdown Mailables](https://laravel.com/docs/5.5/mail#markdown-mailables)

**Comment by changeweb** [comment]
This is perfect. We need to create a basic standard invitation email template with this Markdown mailables. A link to Login page can be added so that the invited person can easily visit the login page.

**Comment by anishojha** [comment]
Hi @changeweb, I have updated the code for standard email template, please check the screenshot and let me know if you want any change here like text change, I will update that and then will create a PR

![image](https://user-images.githubusercontent.com/24322181/55983285-7220c980-5cb8-11e9-90f8-26750e7e1d63.png)

**Comment by changeweb** [comment]
Looks good. But how do the reciever know his/her primary Password created by Master?

**Comment by changeweb** [comment]
I've merged latest changes of this PR after testing. So I'm closing this issue. Good work :+1:

**Comment by anishojha** [comment]
@changeweb thanks.
Should we add welcome email for all users ??

Currently it's for admin account only.

**Comment by changeweb** [comment]
Yes. It would be great. Since users are registered by either Master or Admin, they should be notified about their account getting created.

**Comment by mykeels** [comment]
Hey, this is awesome work!!! 🙌

**Comment by anishojha** [comment]
Okay I will add code for other users also later today and will create a new PR

@changeweb please add steps to readMe file, so other users can know how to setup for email.

@mykeels thanks man!

**Comment by changeweb** [comment]
@anishojha I've made a change in my latest PR with `try{}catch(){}` block to handle fired event to send invitation mail. If Mail is not configured properly in `.env` file then a log message will be logged.

If you're working on this then be sure to add `try-catch` block.

**Comment by anishojha** [comment]
@changeweb great!
Right now I am not working on this, but I will keep this in mind before creating PR

**Comment by changeweb** [comment]
I've added instruction about this in **Good to know** section. But readme.md is getting too big. So I've decided to include further instructions in Wiki. I'll add detail instructions there on Mail configuration and link the wiki in readme.md page.
