### ISSUE TITLE
Cannot issue book to student from librarian account

### ISSUE THREAD

**Issue by farhankarim** [changeweb/Unifiedtransform#74]
**Describe the bug**
when i try to issue a book to student from librarian's account it gives error.

**To Reproduce**
1. Go to 'http://127.0.0.1:8000/library/issue-books' and add information
2. Click on 'Save'
3. Scroll down to 'errors'

**Expected behavior**
the book should be issued by the librarian

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 7
 - Browser:chrome 73.0.3683.86

**Smartphone (please complete the following information):**
NA

**Additional context**
steps i performed after cloning

1. create env file
2. migrate and seed

**Comment by farhankarim** [comment]
![image](https://user-images.githubusercontent.com/19637376/55863684-79e74d80-5b94-11e9-99f1-6098b78d74f8.png)

**Comment by changeweb** [comment]
@farhankarim Nice catch.  I've passed the `$request` variable now to `use($ib, $request)`. I made a Pull request. You can check the updated code and let me know.

**Comment by farhankarim** [comment]
![image](https://user-images.githubusercontent.com/19637376/55865664-49a1ae00-5b98-11e9-8daa-c63afb507de0.png)

**Comment by changeweb** [comment]
@farhankarim replace `'quantity' => ($book->quantity - 1)` with this `'quantity' => \DB::raw('GREATEST(quantity - 1, 0)')`
I've updated the code base.
