### ISSUE TITLE
Important Notice: issue_books column changed

### ISSUE THREAD

**Issue by changeweb** [changeweb/Unifiedtransform#89]
For better handling and future improvement, in 'issue_books' table a column has been changed.

**book_code** changed to **book_id** as a **Foreign key**.

For people who don't have latest changes:

To update your repository's database with this change run `php artisan migrate:refresh --seed`

**Comment by anishojha** [comment]
@changeweb this migration command `php artisan migrate:refresh --seed` will refresh the data, its okay, but what about those users, using your program with real data, they can lost their data, with the above migration command.

**Comment by changeweb** [comment]
@anishojha I know but this is one of the few major changes that need to be done before first stable release of the software. Besides, I think very few people are using this in their production at this rapid development stage. I hope this software will be very stable within next 2 months.

**Comment by anishojha** [comment]
Yes you should create a new branch for this rapid development and fix master branch only for major release.
Although you are doing great work!!! :thumbsup:
