### ISSUE TITLE
Can windows run this project?

### ISSUE THREAD

**Issue by steadfastsnail** [changeweb/Unifiedtransform#94]
window10+wamp64;
when run artisan, show:
In ProviderRepository.php line 208:

  Class 'Rap2hpoutre\LaravelLogViewer\LaravelLogViewerServiceProvider' not found

**Comment by changeweb** [comment]
Ofcourse. Just follow the **How to start** section in readme.md and make sure you have the server requirements such as PHP >= 7.0.0
