### ISSUE TITLE
There are no buttons for creating users

### ISSUE THREAD

**Issue by Smurtta** [changeweb/Unifiedtransform#96]
I'm trying to add new students, but there are no button for this in Manage Schools section.
![изображение](https://user-images.githubusercontent.com/49613570/56093483-0d40bb80-5ed2-11e9-858a-c5a8c55f34c5.png)

**Comment by changeweb** [comment]
Is your Repository up to date with latest master branch? Because I think this issue was solved in this issue #83 . Let me know if this solve your problem.

**Comment by Smurtta** [comment]
Okay, yeah, that helped, but now I faced new problems: I can't assign course teacher, the list is empty.
![изображение](https://user-images.githubusercontent.com/49613570/56095076-c955b280-5ee1-11e9-82c2-c57b968865bc.png)

**Comment by Smurtta** [comment]
Also I have this exeption trying to view the course grades
![изображение](https://user-images.githubusercontent.com/49613570/56095395-0e2f1880-5ee5-11e9-98b1-96b90ce2e99d.png)

**Comment by changeweb** [comment]
@Smurtta Good catch. I've fixed this and now uploading the patch. Please update your code from the master repository.

**Comment by changeweb** [comment]
@Smurtta View Course marks is also fixed in my latest Pull Request.

**Comment by Smurtta** [comment]
I keep doing some tests and discovered one new thing
![изображение](https://user-images.githubusercontent.com/49613570/56097112-f06bae80-5ef8-11e9-9b43-3d454c925f1b.png)

**Comment by changeweb** [comment]
From what url you are getting this new error?
Is your previous problem solved?
If this is a separate problem then please open a new issue.
